---
- name: Install Terraform
  hosts: all
  become: yes
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - gnupg
          - software-properties-common
          - curl
        state: present
        update_cache: yes

    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add HashiCorp APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release|lower }} main"
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Terraform
      apt:
        name: terraform
        state: present
